### ISSUE TITLE
Images that are large won't load

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#220] opened 2022-03-05 13:54 UTC
I finally figured out why some of my students were trying to load an image that they got from their cell phone and were not able to make it show up. The image was 1.5 Mb, and when I rescaled it to 100K, it did load.

We should explicitly say what is the maximum size allowed, maybe not allow to load it if it is too large. what is the limit of the size? 200K?

**Comment by mmicciolo** [comment] 2022-03-07 05:31
Hello @IvonArroyo 

This is a duplicate of #207. I would appreciate if you could check to see if a ticket already exists and then add more information as comments to the existing ticket.

Copying the text above into the already existing issue and closing this one.

Thanks!

**Closed by mmicciolo** 2022-03-07 05:31 UTC
Labels: bug, enhancement
