### ISSUE TITLE
DEV throwing error on autosave

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#218] opened 2022-03-04 18:43 UTC
When my game goes to autosave, it throws this error
![image](https://user-images.githubusercontent.com/32133509/156823037-d795b662-e2e6-4c5d-b320-b3233087bb9b.png)
However, when I log out and log back in, my changes were saved.

**Comment by geseiche** [comment] 2022-03-04 18:54
![image](https://user-images.githubusercontent.com/32133509/156824489-3ee067b4-8865-49f7-9865-ef0cf54d4014.png)

**Comment by mmicciolo** [comment] 2022-03-04 19:17
@geseiche 

This is related to #217 These games are using an older format and I need to upgrade them.

**Comment by mmicciolo** [comment] 2022-03-07 22:42
@IvonArroyo @geseiche 

Closing this issue.

Games have been upgraded and re-uploaded.

Confirmed autosave + copy working as intended.

Anymore or new issues please open new ticket.

Thanks!

**Closed by mmicciolo** 2022-03-07 22:42 UTC
Labels: bug, game editor
