### ISSUE TITLE
Pictures / Images are not displaying in the text box

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#207] opened 2022-02-18 17:23 UTC
- Pictures are not displaying while uploading them during the game creation (We have tried JPEG/PNG/HEIC)
- It's the same issue while uploading the pictures from URL's

This is what happened: 
Krishna took a picture with a cell phone and then attempted to upload in a state (in combination with a bunch of text).
The image didn't show up, even when we tried to display it in another state by itself.

Check the game, it is fractionpyramid on DEV. Try to add an image to the state :"Worked Example".

What surprised me is that the image never showed up in the state box. As if it never manged to load it.

Is it possible that the image was maybe too large? Is there a size limit maybe? If so, we should state that, or make it fail when the image size surpasses a certain byte size.

**Comment by mmicciolo** [comment] 2022-03-07 05:32
Copying @IvonArroyo  comment from #220 

I finally figured out why some of my students were trying to load an image that they got from their cell phone and were not able to make it show up. The image was 1.5 Mb, and when I rescaled it to 100K, it did load.

We should explicitly say what is the maximum size allowed, maybe not allow to load it if it is too large. what is the limit of the size? 200K?

**Comment by mmicciolo** [comment] 2022-03-21 21:54
@IvonArroyo 

I think I found the issue with this one. Its related to the File Dialog popup. Right now a single dialog instance is being used where a new one needs to be created everytime. This is causing the file to not even upload.

Will also add some waiting indicators while the file uploads.

**Comment by mmicciolo** [comment] 2022-04-08 16:23
This bug has been fixed and is waiting deployment to dev.

**Comment by mmicciolo** [comment] 2022-04-14 00:37
This fixes a bug where you cannot upload multiple files in a row in the state editor dialog.

**Testing Instructions**

1. Open the game editor
2. Create a new game with one state
3. For team 1 upload a photo, video and sound
4. For team 2 upload a different photo, video and sound
5. Go back to team 1 and upload the different photo,video and sound from step 4. Make sure URLs change and the file uploads

All files should upload with no issues. Larger files that take longer than 1 sec a busy indicator will appear until after the upload is complete.

**Comment by apoh3** [comment] 2022-05-04 18:58
**Test passed**

No issues uploading photos, videos, or sound - urls & image preview updated after change. Busy indicator displayed for large files.

**Comment by franciscastro** [comment] 2022-05-18 19:57
**Test failed**

All descriptions below pertain to interactions within the _State editor_.

Completed uploading photo, video, and sound to team 1. 

Uploaded different photo, video, and sound to team 2, however, the sound that plays for team 2 is the same sound from team 1, even after having repeatedly changed the sound clip used.

Another observation is that if I play a video and then switch to the other media types (e.g., text, photo, sound), the video keeps playing in the background instead of pausing automatically.

Notes:
- Game tested: `francis-test-issue207`
- Video uploaded to team 1: 2.5 MB (portrait-style video of a bridge)
- Video uploaded to team 2: 8.5 MB (landscape-style video of a sunset over the ocean)
- Sound uploaded to team 1: 295 KB, .wav format (video game sound)
- Sound uploaded to team 2: 286 KB, .wav format (dog barking)
- Photos uploaded to team 1 and 2 are just different screenshots of the WearableLearning game editor.

**Comment by apoh3** [comment] 2022-05-18 20:17
Tested again and **failed**

Running into the same issues as @franciscastro. For example, if I set player 1 to goat sound and player 2 to water sound and then back to player 1 to dog sound, the url does update but the sound is still goat instead of dog. Also, if a sound is playing and I leave the state editor without pressing pause, the sound continues to play.

**Comment by sai-educ** [comment] 2022-06-01 03:58
Tested on June 1, 2022. Noticed the same issue that @franciscastro and @apoh3 reported. Audio file from team1 plays in team2. 

Also noticed that when you save the game (game name is 207), load any other unrelated game, and then load the 207 game, the picture under team1 does not show by default and only the picture under team2 shows. However, when you adjust the resize slider, team1 image quickly appears. Requesting others to confirm.

**Comment by mmicciolo** [comment] 2022-06-23 01:09
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for retesting of newly found bugs:

If a sound or video was playing, the sound/video would not stop in the following cases:

1. Playing and user selects a new scope (eg team 1 then clicks team 2)
2. Playing and change state configs (eg play sound then clicks display text)
3. Playing and click accept button
4. Playing and click close button

**Testing:**
Repeat the steps below for both sound and video:

1. Create a test game with a single state
2. Add a sound/video to the state
3. Start the sound/video
4. Change scopes (eg team 1 to team 2) and sound/video should stop
5. Start the sound/video
6. Change state configs (eg change from sound to display text) and sound/video should stop
7. Start the sound/video
8. Click the accept button sound/video should stop
9. Start the sound/video
10. Click the close button and sound/video should stop

**Comment by apoh3** [comment] 2022-06-24 13:54
**Test passed**

Sound/video stops playing any time I click a button that leaves the Play Sound/Play Video option.

**Comment by franciscastro** [comment] 2022-07-08 16:51
**Test *partially* passed**

Sound/video stops playing any time a button that leaves the Play Sound/Play Video option is clicked.

---
**Bug found**

Scenario: Video is "successfully uploaded" as the object URL is available after uploading, but the video preview is not available and can't be played. See screenshot below.

<img width="1220" alt="Screen Shot 2022-07-08 at 12 31 45 PM" src="https://user-images.githubusercontent.com/1910413/178035920-83d737d1-10b1-48e5-9e66-68b68d414b50.png">

Notes:

- Game tested: test-game
- Video uploaded to team 2: 8.5 MB (landscape-style video of a sunset over the ocean)

**Comment by mmicciolo** [comment] 2022-07-08 18:38
Hello @franciscastro 

Unable to reproduce this. Video stays white for a few seconds after uploading while it is re-downloaded from the server to display.

Does it eventually load if you wait?

Are there any errors in the debug console.

**Comment by mmicciolo** [comment] 2022-07-21 19:20
Closing for now. Will reopen if we experience further issues.

Will open new ticket for explicitly stating max upload size.

**Closed by mmicciolo** 2022-07-21 19:20 UTC
Labels: bug, enhancement, game editor, ready for testing

**Comment by franciscastro** [comment] 2022-08-18 18:50
Ticket for max upload size here: #255
