### ISSUE TITLE
Logging in for a player & Simplified Main Login

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#126] opened 2021-04-14 21:47 UTC
I have been learning a lot about how to allow final users (students) to log in to a learning system.
It has to be REALLY easy.
I don't think they should need accounts with passwords to login, it is too hard.
It should be enough to enter the PIN. Maybe it can ask for their first name, for our records, and to save in the DB.

**Comment by IvonArroyo** [comment] 2021-04-14 21:48
We could have a special button in the login page that says "Just Play!", and that way they don't have to login.

**Comment by franciscastro** [comment] 2022-02-03 00:46
@geseiche Will be writing the test script for this, with @mmicciolo reviewing for coverage

**Comment by geseiche** [comment] 2022-02-18 12:08
This issue is about enhancing login so accounts are not required for students to play the games.

When entering the WLCP, instead of being forced to log in, there is an option to Log In or Play a Game.
![image](https://user-images.githubusercontent.com/32133509/154679225-a232ebae-672e-441c-bcbc-12ff1134bf50.png)

Players can click play a game and then they are immediately directed to enter a game pin and choose a player, eliminating the need to log in with a username and password.
![image](https://user-images.githubusercontent.com/32133509/154679432-a2f90db3-8d29-41a5-9c38-01e2cdae04df.png)

Testing No Login Playing
1. Navigate to the [Log In Page](https://dev.wearablelearning.org/wlcp-ui/index.html#/RouteLoginView)
2. Click "Play a game!"
3. Enter a game pin
Success if you can play a game with being prompted to log in

Testing Logged In Playing
1. Navigate to the [Log In Page](https://dev.wearablelearning.org/wlcp-ui/index.html#/RouteLoginView)
2. Click "Log In"
3. Enter log in credentials
4. Click "Game Player"
5. Enter a game pin
Success if you can play a game

For your convenience, the following game pins are active: 41 and 42

**Comment by geseiche** [comment] 2022-02-18 12:10
@mmicciolo Test script is ready for approval

Also, do we need to make a separate issue adding a "Play game button" to the website (wearablelearning.org)?

**Comment by franciscastro** [comment] 2022-02-23 02:46
> @mmicciolo Test script is ready for approval
> 
> Also, do we need to make a separate issue adding a "Play game button" to the website (wearablelearning.org)?

@geseiche @mmicciolo If I remember correctly from a previous meeting, we will be adding the issue ticket for "Add a Play Game button" to the website once this feature has been merged to production

**Comment by franciscastro** [comment] 2022-02-23 03:01
**Test Scenario:** No Login Playing

**Results**: 
- Functional -- I was able to play game PINs 41 and 42 without being prompted to log in

---

**Test Scenario:** Logged In Playing

**Results:**
- Functional -- I was able to play game PINs 41 and 42 while logged into my account

---

**Other findings**
- I found a bug with game PIN 41 (Tangrams Race) where the labels for the buttons are appearing as `null` (see screenshot). This bug appears in multiple screens of the game and happens for both the "No Login" and "Logged In" test scenarios. @mmicciolo, is this related to the moving of games from the production server to the dev server?

**Other details:**
- Browser used: Mozilla Firefox

**Screenshots:**
<img width="777" alt="Screen Shot 2022-02-22 at 9 49 05 PM" src="https://user-images.githubusercontent.com/1910413/155254336-74da4b29-f988-4e78-8c6a-4e5052940788.png">
<img width="702" alt="Screen Shot 2022-02-22 at 9 57 09 PM" src="https://user-images.githubusercontent.com/1910413/155254857-02f8b023-a3fd-433d-83c0-7d8a5f71827f.png">

**Comment by mmicciolo** [comment] 2022-02-23 03:54
Thanks for starting to test this Francis.

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by sai-educ** [comment] 2022-02-28 21:47
**Both "No Logging Playing" and "Logged in Playing" working as intended.** Requesting two more testers.

Testing scenario:  No Login Playing
- Generated a game pin before hand for the purpose of testing this issue
- Open login portal [here](https://dev.wearablelearning.org/wlcp-ui/index.html#/RouteLoginView)
- Selected "Play a game!" and entered the game pin
- System prompts for player name and game begins

Testing scenario: Logged In Playing
- Open login portal [here](https://dev.wearablelearning.org/wlcp-ui/index.html#/RouteLoginView)
- "Log In" and entered credentials
- Selected "Game Player" and entered a game pin
- Game begins successfully

**Comment by apoh3** [comment] 2022-03-02 18:37
@mmicciolo @franciscastro @geseiche @sai-educ 

**Tests Passed**

Both tests worked for the open games (41 and 42) as well as a game I opened (151).

For game pin 41, I also see nulls for button presses (referring to @franciscastro's comment). I created a new game pin for Tangrams Race (151) and do not see nulls (says Red Button, Green Button, etc.)

**Comment by apoh3** [comment] 2022-03-02 21:27
@mmicciolo @franciscastro @geseiche @sai-educ @IvonArroyo @apoh3 
All testing complete.

**Closed by apoh3** 2022-03-02 21:27 UTC
Labels: enhancement, high priority, game player, ready for testing, ext-tracker
