### ISSUE TITLE
Game Editor:: Undo/Redo Functionality

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#27] opened 2020-03-31 20:43 UTC
Several participants asked if there was an undo button.

Undo, if they had not saved, would allow them to go back in time to undo things that really messed up their games.

**Comment by mmicciolo** [comment] 2021-09-29 03:17
Remaining tasks:
1. i18n
2. Cleanup
3. Further testing
4. Chain call load?

**Comment by mmicciolo** [comment] 2021-12-22 21:59
Starting a new TODO list:

- 1
- 2

**Comment by mmicciolo** [comment] 2022-02-18 17:17
This issue adds undo/redo functionality to the game editor. It accomplishes this by adding 2 new buttons to the main tool bar at the top.

When you first create a new game or load an existing game both of the buttons should be greyed out

![image](https://user-images.githubusercontent.com/23061418/154729859-6729f837-076f-45bc-8ca9-8b346ef205ca.png)

The following actions will allow you to undo/redo:

add state
add connection
add transition

edit state
edit transition

move state

delete state
delete connection
delete transition

After performing one of these actions the undo button should be selectable. In the picture below a state has been added.

![image](https://user-images.githubusercontent.com/23061418/154730220-7ea23a83-d7f9-4478-a27e-a3190368f2a4.png)

Clicking the undo button removes that states and allows the redo button to be selectable.

![image](https://user-images.githubusercontent.com/23061418/154730299-fe83cef4-459f-49db-90b5-f32d8b3ed314.png)

If you make multiple moves and undo a few times without going all the way back to the beginning, both buttons will be enabled.

![image](https://user-images.githubusercontent.com/23061418/154730505-04532668-af4e-47c4-91cc-a21afedd45bb.png)

![image](https://user-images.githubusercontent.com/23061418/154730525-d28ed7cc-8f63-4395-bb61-ed47eee0360d.png)

Making another change will reset the redo queue. Ex i moved the state so the redo button is no longer selectable and I cannot redo the add state above.

![image](https://user-images.githubusercontent.com/23061418/154730867-e42ea6df-49d4-42f6-a6cd-29ea66ec7543.png)

**Comment by mmicciolo** [comment] 2022-02-19 02:47
@IvonArroyo @franciscastro @sai-educ  @geseiche @apoh3 

Ready for testing. Will need at least 2-3 testers per issue.

May make a few updates to the test instructions on this one.

Thanks!

**Comment by mmicciolo** [comment] 2022-03-01 19:53
@sai-educ 

Are you doing this testing locally or on dev.wearablelearning.org ?

Can't find that game "27"

**Comment by apoh3** [comment] 2022-03-02 18:27
@mmicciolo @franciscastro @geseiche

**Test failed**

Received error when deleting the final state:
![image](https://user-images.githubusercontent.com/61091501/156424397-08ad415c-0771-408e-8118-c0a6e19258eb.png)
![image](https://user-images.githubusercontent.com/61091501/156424434-a99e6a48-c97f-43fa-a6da-4521e311395a.png)

All other tests passed.

**Comment by apoh3** [comment] 2022-03-30 11:11
**Test passed**

Undo/Redo worked for all 9 actions listed, including inputs in state and transition editors.

**Comment by sai-educ** [comment] 2022-03-30 18:16
**Test passed.** 

All 9 actions working as intended.

**Comment by mmicciolo** [comment] 2022-03-30 20:11
Testing complete. Closing issue.

**Closed by mmicciolo** 2022-03-30 20:11 UTC
Labels: enhancement, game editor, ready for testing, ext-tracker
