### ISSUE TITLE
Errors in Console when double clicking on states or transition

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#137] opened 2021-06-30 19:22 UTC
Hi Matt,

I made a small program, called MyTest for user iarroyo/iarroyo. It uses random variables and delays.

I found several times in the process that suddenly I couldn't double click and open a transition or a state. I checked the console and I saw a lot of red errors. I attach the console screenshot.

This might have happened after I added and deleted a state (I was trying to add another state, in the middle of existing ones, rerouting all the arrows to fit this new one in the middle).

<img width="1113" alt="122461413-5349ac00-cf81-11eb-9285-e2cfbb50581e" src="https://user-images.githubusercontent.com/5631787/124019382-fd302c00-d9b6-11eb-97bd-0a7323659ee9.png">

**Comment by mmicciolo** [comment] 2021-09-12 20:31
Closing due to the fact this is a duplicate of #115 

It is related to a bigger issue and all further progress will be tracked in #115

**Closed by mmicciolo** 2021-09-12 20:31 UTC
