### ISSUE TITLE
[BUG - WearableLearning Platform Directory Publicly Accessible]

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#248] opened 2022-06-22 22:37 UTC
**Describe the bug**
The directory listing of https://dev.wearablelearning.org/ is visible to the public. 

**To Reproduce**
1. Go to https://dev.wearablelearning.org/
2. URL automatically routes to https://dev.wearablelearning.org/wlcp-ui
3. Remove the "index.html#/RouteLoginView" part of the URL
4. Directory listing of the WearableLearning platform is now visible to the public

**Expected behavior**
The directory listing of the WearableLearning platform should **not** be visible to the public.

---

**Screenshots**

![image](https://user-images.githubusercontent.com/1910413/175165428-962f2108-c167-4220-ac29-3240d66c742f.png)

---

**Desktop (please complete the following information, write N/A if not applicable):**
 - OS: Windows
 - Browser: Google Chrome

**Smartphone (please complete the following information, write N/A if not applicable):**
 - Device: Pixel 5
 - OS: Android
 - Browser: Google Chrome

---

**Additional context**
N/A

**Comment by mmicciolo** [comment] 2023-03-12 18:26
@apoh3 @franciscastro @sai-educ @IvonArroyo 

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
It used to be possible for the public to view the directory listing of the ui web server.

**Testing Steps**

1. Go to https://dev.wearablelearning.org/
2. URL automatically routes to https://dev.wearablelearning.org/wlcp-ui
3. No index.html is displayed in address bar
4. Remove the "#/RouteLoginView" part of the URL
5. Directory listing of the WearableLearning should not be visible and should be redirected to main page

**Expected Results**
User should not be able to get to the directory listing. Index.html will not be shown in address bar.

**Comment by apoh3** [comment] 2023-05-31 13:43
**Test passed**

https://dev.wearablelearning.org/ routed me to:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/98d3ecf3-92b8-48a9-a976-2af5cbd2a1e7)

Removing #/RouteLoginView routed me to:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/c53adeb5-8550-4723-acf2-9241be2228a6)
which quickly updated
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/98d3ecf3-92b8-48a9-a976-2af5cbd2a1e7)

Trying to go to https://dev.wearablelearning.org/wlcp-ui/index.html routed me to:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/8bf94727-3fc4-4274-bd99-8ac99cd74325)

**Comment by sai-educ** [comment] 2023-05-31 17:17
Test passed. Working as intended.

**Comment by mmicciolo** [comment] 2023-08-28 00:10
Testing complete. Deployed to Prod. Closing Issue.

**Closed by mmicciolo** 2023-08-28 00:10 UTC
Labels: bug, high priority, Login, ready for testing
