### ISSUE TITLE
Error when copying Game

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#205] opened 2022-02-10 19:24 UTC
I was trying to copy the tangrams race (so that I could remove the trophy from the first state). I managed, but I get an error when I got to save that new game. The error is attached
![Screen Shot 2022-02-10 at 2 22 11 PM](https://user-images.githubusercontent.com/5631787/153481654-c37c35af-e3a7-4378-9e57-14e1af193121.png)
:

**Comment by mmicciolo** [comment] 2022-03-07 22:42
@IvonArroyo @geseiche 

Closing this issue.

Games have been upgraded and re-uploaded.

Confirmed autosave + copy working as intended.

Anymore or new issues please open new ticket.

Thanks!

**Closed by mmicciolo** 2022-03-07 22:42 UTC
Labels: bug
