### ISSUE TITLE
[BUG - Game Editor] Escape keyboard press disables Game Editor dialog instances

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#256] opened 2022-07-28 20:09 UTC
**Describe the bug**
Pressing the Escape keyboard button when any of the Game Editor dialog boxes are open exits the dialog boxes but disables future instances of the dialog boxes. For example, double-clicking the State editor and then pressing Escape exits the State editor dialog but will not open the State dialog again on future attempts. The dialog boxes won't appear again until the browser is refreshed or the you log out and log back in.

**To Reproduce**
1. Create a new game and add a state, or load an existing game
2. Double-click a state to open the State editor dialog
3. Press the Escape button on your keyboard - this would exit the State editor dialog
4. Double-click the same state - the State editor dialog will not open at this point

**Expected behavior**
Pressing Escape should not exit any of the dialogs in the Game Editor. Dialogs should exit only after pressing an exit-function button (_e.g._, "Cancel" or "Close")

---

**Screenshots**
n/a

---

**Desktop (please complete the following information, write N/A if not applicable):**
 - OS: Mac
 - Browser: Mozilla Firefox, Google Chrome

**Smartphone (please complete the following information, write N/A if not applicable):**
n/a

---

**Additional context**
This bug behavior is triggered for any dialogs in the Game Editor - _e.g._, New, Load, Transition editor, etc.

**Comment by mmicciolo** [comment] 2022-07-29 03:36
@franciscastro @apoh3 @geseiche @IvonArroyo

Ready for testing at https://prod.wearablelearning.org/

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1

Test all of the following dialogs. Make sure pressing the esc key doesn't close them.
- New
- Load
- Save
- Run and Debug
- History
- Getting Started
- Copy Game
- Rename Game
- Delete Game
- Game Properties
- Start state
- Output State
- Transition
- Start Game Instance
- Transition Color Sequence -> Add Sequence
- Transition Text Entry -> Add Text Entry

**Steps for testing**
1. Create a new test game
2. Make sure to cleanup the game after since we are testing on prod
3. Test all of the following dialogs above
4. Open them
5. Confirm that pressing the esc key does not close them

**Expected behavior**
No more errors with esc key closing dialogs and not cleaning them up properly.

**Screenshots**
n/a

---

# Additional context
n/a

**Comment by apoh3** [comment] 2022-08-09 16:03
**Test failed for 1 case: History**

Selecting History and pressing Escape closes the History popup. All other cases passed.

**Additional comment:** 
If new text is written in a text field and the text field is still in focus, pressing escape erases that new text. 
**Example 1:** Select New, type anything under Game Name, and press Escape. The game name entered is now erased. 
**Example 2:** Open a state, type anything in the Display Text text field, select Accept, open that state again, type additional text into the same text field, and press Escape. The newest text is erased. 
I'm not sure if this is an expected behavior.

**Comment by sai-educ** [comment] 2022-09-15 01:28
Test failed for:

In Game Editor: 
1. Load >> enter any search string in the Search box. Hitting Escape key cancels the search. 
2. New >> type any name under Game Name and press Esc. @apoh3 also reported this.
3. Run and Debug >> The virtual phone screen appears to be responding to Esc key on the player selection drop down.
4. History closes when Esc key pressed. @apoh3 reported this.
5. Game Options closes when Esc key pressed
6. Closing "currently open debuggers" will close when Esc key is pressed
7. State Title text and on-screen display text - both appear to be reverting to old text when Esc is pressed

In Game Manager:
1. Start a game >> select drop down and press Esc.

In Game Player:
1. Enter any random pin in Game PIN box. Press Esc and it will clear
2. Player selection dropdown closes when Esc pressed

**Comment by mmicciolo** [comment] 2022-09-24 18:52
Thank you @apoh3 and @sai-educ for testing.

> In Game Editor: 
> 1. Load >> enter any search string in the Search box. Hitting Escape key cancels the search. 
> 2. New >> type any name under Game Name and press Esc. @apoh3 also reported this.
> 3. Run and Debug >> The virtual phone screen appears to be responding to Esc key on the player selection drop down.
> 4. History closes when Esc key pressed. @apoh3 reported this.
> 5. Game Options closes when Esc key pressed
> 6. Closing "currently open debuggers" will close when Esc key is pressed
> 7. State Title text and on-screen display text - both appear to be reverting to old text when Esc is pressed
> 
> In Game Manager:
> 1. Start a game >> select drop down and press Esc.
> 
> In Game Player:
> 1. Enter any random pin in Game PIN box. Press Esc and it will clear
> 2. Player selection dropdown closes when Esc pressed

Escape needs to be disabled for accept / cancel dialogs only to disable the press of esc closing the dialog without going through the closing sequence. Pop outs are fine, clearing inputs are fine, reverting input is fine

Game editor:
1. For load dialog hitting escape on search dialog is fine
2. For new dialog hitting escape on input fields is fine
3. Run and debug escape on player selection is fine
4. History is considered a game popout and hitting escape is fine
5. Game options is considered a game popout and hitting escape is fine
6. "Currently opener debuggers" is considered a game popout and hitting escape is fine
7. Reverting text via esc is fine

Game manager:
1. Start a game press esc to cancel drop down is fine

Game player:
1. Esc to clear game pin is fine
2. Esc to clear player selection is fine

Testing complete.

Closing issue.

**Closed as completed by mmicciolo** 2022-09-24 18:52 UTC
Labels: bug, game editor, high priority, testing complete, hotfix
