### ISSUE TITLE
Copying Game (on DEV) Throws Error 

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#217] opened 2022-03-03 17:44 UTC
I need to copy the Tangrams Race and the Integer Hopscotch games, as they refer to 'dragging' instead of tapping colors.

If this cannot be fixed, can you make me owner of those two games? (iarroyo). Otherwise, can you tell me the usernames and password of the owner of those games?

Thanks

**Comment by geseiche** [comment] 2022-03-04 18:42
Hi Ivon, 

I am fixing Tangrams Race and can do Integer Hopscotch as well. 

Leaving this open for @mmicciolo to review the bug

**Comment by mmicciolo** [comment] 2022-03-04 19:08
@IvonArroyo @geseiche 

This is a bug only with these games because they are using an older game format. 

The games needs to be upgraded. After grace is done making the changes I can upgrade their format.

**Comment by mmicciolo** [comment] 2022-03-07 22:42
@IvonArroyo @geseiche 

Closing this issue.

Games have been upgraded and re-uploaded.

Confirmed autosave + copy working as intended.

Anymore or new issues please open new ticket.

Thanks!

**Closed by mmicciolo** 2022-03-07 22:42 UTC
Labels: bug, game editor
