### ISSUE TITLE
Game Player: Update the aesthetics of the Player

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#161] opened 2021-11-08 21:23 UTC
Some aspects that would improve the player a lot would be:

1. Background should be white or very light gray
2. Username should be visible at the top
3. Team should be visible at the top
4. Font size should be adjusted depending on the number of characters

**Comment by mmicciolo** [comment] 2021-12-23 03:42
Closing. Duplicate of #36

**Closed by mmicciolo** 2021-12-23 03:42 UTC
Labels: enhancement, game editor, game player
